inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3

# Trailing dots
Layout/DotPosition:
  EnforcedStyle: trailing

# Blocks can be any length in spec files
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

# Be lenient with line length
Metrics/LineLength:
  Max: 110

Naming/PredicateName:
  NameWhitelist:
    - 'has_one'
    - 'has_many'
    - 'has_xml_content'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*_spec.rb'

# Use older RuboCop default
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': ()

# Configuration parameters: AutoCorrect, EnforcedStyle.
# SupportedStyles: predicate, comparison
Style/NumericPredicate:
  EnforcedStyle: comparison
