language: ruby

dist: xenial

cache:
  bundler: true

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-9.1
  - jruby-9.2
  - jruby-head
  - ruby-head

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head

branches:
  only:
    - master
